### ISSUE TITLE
Be able to upload images

### ISSUE THREAD

**Issue by NimaBoscarino** [alumni-lab/many-faced-god#3]
Images should be saved serverside. It doesn't really matter if they're saved to a database or just in the filesystem. Don't worry about clashing filenames.

**Comment by NimaBoscarino** [comment]
This might be a good example: https://medium.com/signature-networks/file-upload-with-node-js-react-js-686e342ad7e7

Same with this: https://codeburst.io/asynchronous-file-upload-with-node-and-react-ea2ed47306dd

**Comment by benjdelt** [comment]
Ben and Nick

**Comment by NimaBoscarino** [comment]
#8 Accomplishes this
